/*CONSULTA DE AGRUPAMIENTO*/
SELECT COUNT(titulo) AS 'NUMERO DE ENTRADAS', categoria_id 
FROM entradas GROUP BY categoria_id;

/*EL WHERE ACTUA SOLO SOBRE UNA COLUMNA, EN CAMBIO EL HAVING CON MAS.*/

/*CONSULTAS DE AGRUPAMIENTO CON CONDICIONES*/
SELECT COUNT(titulo) AS 'NUMERO DE ENTRADAS', categoria_id
FROM entradas GROUP BY categoria_id HAVING COUNT(titulo) >= 4;

/*FUNCIONES DE AGRUPAMIENTO:

MIN -> EL MINIMI VALOR
MAX -> EL MAXIMO VALOR
AVG -> MEDIA DE TODOS LOS VALORES
COUNT -> CONTAR LOS VALORES
SUM -> SUMAR LOS VALOR

*/


SELECT MAX(id) AS 'Maximo id', titulo FROM entradas;
SELECT AVG(id) AS 'Media de id' FROM entradas;
SELECT SUM(id) as 'Suma de id' FROM entradas;